title: Anqian(Irene) Li # your name (or website title) here
logo: "/images/profile_logo3.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>About<br>
  <br>
  I am currently a postgraduate student from the Imperial College London MSc Business Analytics programme. Graduated from UCLA in 2019 with a bachelor degree in applied mathematics and a minor in statistics, I have solid background in mathematics, statistics and data analysis. I have experience in working on projects using R and python to perform exploratory data analysis and data modeling. 
  <br><br>
  <a href="https://www.linkedin.com/in/anqian-li-28a503153//">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
