title: Anqian(Irene) Li # your name (or website title) here
logo: "/images/profile_logo3.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>About<br>
  <br>
  Throughout my work experience, I have solid my skills in translating complex data into understandable insights. I have experience creating visualizations and reports that effectively communicate findings to both technical and non-technical stakeholders. To backup my analytics skill, I have built strong technical background from university and work experience. I am proficient in SQL, Python and R for performing data extraction, exploratory analysis and data modeling. To better deliver insights, I am also proficient in data visualization tools such as Tableau or AWS Quicksight. I am also familiar with statistical techniques and have utilized methods such as regression analysis and predictive modeling in my previous projects.
  <br><br>
  <a href="https://www.linkedin.com/in/anqian-li-28a503153//">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
